use_frameworks!

platform :ios, '10.0'

target 'SubModuleTester_Example' do
  pod 'SubModuleTester', :path => '../'

  target 'SubModuleTester_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
